services:
  mysql:
    image: mysql:8.4
    container_name: car-rental-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - "./car-rent/mysql_setup.sql:/docker-entrypoint-initdb.d/mysql_setup.sql:ro"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .

    container_name: car-rental-app
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}

    ports:
      - "5000:5000"

volumes:
  mysql_data: